# Generated by Django 4.2.7 on 2023-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolista',
            fields=[
                ('TodolistaId', models.AutoField(primary_key=True, serialize=False)),
                ('TodolistaNome', models.CharField(max_length=100)),
            ],
        ),
    ]
